export const BREAKS = [
    {
        startDate: new Date(2024, 7, 1),
        endDate: new Date(2024, 7, 1),
        name: 'First Day Of School',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 8, 2),
        endDate: new Date(2024, 8, 2),
        name: 'Labor Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 22),
        endDate: new Date(2024, 8, 28),
        name: 'Fall Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 9, 21),
        endDate: new Date(2024, 9, 21),
        name: 'Professional Dev. (Student Holiday)',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 10, 5),
        endDate: new Date(2024, 10, 5),
        name: 'Election Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 25),
        endDate: new Date(2024, 8, 26),
        name: 'Hurricane Helene Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 9, 8),
        endDate: new Date(2024, 9, 10),
        name: 'Hurricane Milton Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 10, 24),
        endDate: new Date(2024, 10, 30),
        name: 'Thanksgiving Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 11, 21),
        endDate: new Date(2025, 0, 5),
        name: 'Winter Break',
        type: 'Break',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 2, 30),
        endDate: new Date(2025, 3, 6),
        name: 'Spring Break',
        type: 'Break',
    },
];

export const EVENT_DATA = [
    {
        id: 'e1',
        name: 'Homecoming Football Game',
        date: new Date(2024, 9, 21),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Annual homecoming game between Lambert High School and South Forsyth High School',
        ticketCost: 20,
        eventOrganizers: 'LHS Athletics Department',
        specialNotes: 'Parking Lot A and B, masks encouraged',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e2',
        name: 'Winter Dance',
        date: new Date(2024, 11, 10),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description: 'Semi-formal dance for students, with live DJ',
        ticketCost: 35,
        eventOrganizers: 'LHS Student Council',
        specialNotes: 'Formal attire required, no re-entry policy',
        socialMedia: 'Instagram, Snapchat',
    },
    {
        id: 'e3',
        name: 'School Play: "Romeo & Juliet"',
        date: new Date(2024, 10, 15),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Theater',
        location: 'Auditorium',
        description:
            "Drama club production of Shakespeare's classic, Romeo and Juliet.",
        ticketCost: 15,
        eventOrganizers: 'State Drama Council',
        specialNotes: 'Limited seating, early booking is advised',
        socialMedia: 'Facebook, Instagram',
    },
    {
        id: 'e4',
        name: 'Annual Science Fair',
        date: new Date(2025, 0, 24),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Science fair featuring projects from students in grades K-12',
        ticketCost: 0, // free
        eventOrganizers: 'Science Club',
        specialNotes:
            'Parking in Lot A only! Drivers who park in Lot B will automatically be escorted out.',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e5',
        name: 'Holiday Charity Concert',
        date: new Date(2024, 11, 18),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Holiday concert with performances by the school choir!',
        ticketCost: 20,
        eventOrganizers: 'LHS Music Department',
        specialNotes: 'Donations for charity are accepted.',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e6',
        name: 'Craft Fair 2024',
        date: new Date(2024, 10, 2),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Arts',
        location: 'Main Gymnasium',
        description:
            'Local artisan craft fair for the people interested in arts!',
        ticketCost: 10,
        eventOrganizers: 'Art Club',
        specialNotes: 'Open to the public',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e7',
        name: 'Parent-Teacher Night Conference',
        date: new Date(2024, 10, 4),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description: 'Official Meet and Greet for parents and teachers!',
        ticketCost: 0,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: '',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e8',
        name: 'Annual Science Fair',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T17:30:00'),
        type: 'Academic',
        location: 'Cafeteria',
        description:
            'Science Fair: Showcase your awesome science projects for our students!',
        ticketCost: 5,
        eventOrganizers: 'Science Club',
        specialNotes:
            'People who do not pay the ticket fee are restricted to certain parts of the exhibit.',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e9',
        name: 'Movie Night: Screening of "Back into the Future"',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T15:00:00'),
        endTime: new Date('1970-01-01T18:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description:
            'Indoor screening of the "Back into the Future!", a revolutionary movie that will change your life for the better!',
        ticketCost: 5,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: 'Blankets and chairs will NOT be provided!',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e10',
        name: 'Halloween Costume Contest',
        date: new Date(2024, 9, 31),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description:
            'Annual Halloween costume contest with prizes for the best costumes!',
        ticketCost: 5,
        eventOrganizers: 'Student Council',
        socialMedia: 'Instagram, Facebook',
    },
    {
        id: 'e11',
        name: 'Chess Club Tournament',
        date: new Date(2024, 10, 6),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Inter-school chess tournament with competitors from various schools.',
        ticketCost: 0,
        eventOrganizers: 'Chess Club',
        socialMedia: 'Instagram',
    },
    {
        id: 'e12',
        name: 'School Drama Production',
        date: new Date(2024, 10, 10),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T21:30:00'),
        type: 'Theater',
        location: 'Auditorium',
        description: 'Annual fall drama production by the theater club.',
        ticketCost: 12,
        eventOrganizers: 'Theater Club',
        socialMedia: 'Facebook',
    },
    {
        id: 'e12',
        name: 'Winter Band Performance',
        date: new Date(2024, 11, 1),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T20:30:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Annual winter concert by the school band.',
        ticketCost: 15,
        eventOrganizers: 'Music Club',
        specialNotes:
            'Some parts of the seats will not be available for the time being (may change)',
        socialMedia: 'Facebook, Twitter',
    },
    {
        id: 'e13',
        name: 'Varsity Soccer Practice',
        date: new Date(2025, 0, 11),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T18:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description: 'Practice session for the varsity soccer team.',
        ticketCost: 0,
        eventOrganizers: 'Athletics Department',
        specialNotes:
            'People who sign up for this event will only be able to watch the kids practice.',
        socialMedia: 'Twitter',
    },
    {
        id: 'e14',
        name: 'Basketball Finals',
        date: new Date(2024, 11, 20),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Sports',
        location: 'Main Gymnasium',
        description: 'Championship game for varsity basketball.',
        ticketCost: 12,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Twitter',
    },
    {
        id: 'e15',
        name: 'Regional Wrestling Meet',
        date: new Date(2025, 0, 20),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Regional wrestling tournament with multiple schools competing.',
        ticketCost: 10,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Facebook',
    },
];
