export const BREAKS = [
    {
        startDate: new Date(2024, 7, 1),
        endDate: new Date(2024, 7, 1),
        name: 'First Day Of School',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 8, 2),
        endDate: new Date(2024, 8, 2),
        name: 'Labor Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 22),
        endDate: new Date(2024, 8, 28),
        name: 'Fall Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 9, 21),
        endDate: new Date(2024, 9, 21),
        name: 'Professional Dev. (Student Holiday)',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 10, 5),
        endDate: new Date(2024, 10, 5),
        name: 'Election Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 25),
        endDate: new Date(2024, 8, 26),
        name: 'Hurricane Helene Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 9, 8),
        endDate: new Date(2024, 9, 10),
        name: 'Hurricane Milton Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 10, 24),
        endDate: new Date(2024, 10, 30),
        name: 'Thanksgiving Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 11, 21),
        endDate: new Date(2025, 0, 5),
        name: 'Winter Break',
        type: 'Break',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 2, 30),
        endDate: new Date(2025, 3, 6),
        name: 'Spring Break',
        type: 'Break',
    },
    {
        startDate: new Date(2025, 1, 14),
        endDate: new Date(2025, 1, 14),
        name: 'Valentines Day',
        type: 'Holiday',
    },
];

export const CONVENIENCE_FEE = 2;
export const SEATS_PER_ROW = 30;
export const EVENT_DATA = [
    {
        id: 'e1',
        name: 'Homecoming Football Game',
        date: new Date(2024, 11, 16),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Annual homecoming game between Lambert High School and South Forsyth High School',
        ticketCost: 20,
        eventOrganizers: 'LHS Athletics Department',
        specialNotes: 'Parking Lot A and B, masks encouraged',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1A23', '1A24', '1A25', '3B13', '3B14'],
    },
    {
        id: 'e2',
        name: 'Winter Dance',
        date: new Date(2024, 11, 10),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description: 'Semi-formal dance for students, with live DJ',
        ticketCost: 35,
        eventOrganizers: 'LHS Student Council',
        specialNotes: 'Formal attire required, no re-entry policy',
        socialMedia: 'Instagram, Snapchat',
        takenSeats: ['3F14', '3F15', '2H3', '2H19', '1A14', '1A21'],
    },
    {
        id: 'e3',
        name: 'School Play: "Romeo & Juliet"',
        date: new Date(2024, 10, 15),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Theater',
        location: 'Auditorium',
        description:
            "Drama club production of Shakespeare's classic, Romeo and Juliet.",
        ticketCost: 15,
        eventOrganizers: 'State Drama Council',
        specialNotes: 'Limited seating, early booking is advised',
        socialMedia: 'Facebook, Instagram',
        takenSeats: ['1A14', '1A21', '1A22', '1A23', '1A24', '1A25', '3B13', '3B14'],
    },
    {
        id: 'e4',
        name: 'Annual Science Fair',
        date: new Date(2025, 0, 24),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Science fair featuring projects from students in grades K-12',
        ticketCost: 0, // free
        eventOrganizers: 'Science Club',
        specialNotes:
            'Parking in Lot A only! Drivers who park in Lot B will automatically be escorted out.',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1A14', '1A21', '1A22', '1A23', '1A24', '1A25', '3B13', '3B14'],
    },
    {
        id: 'e5',
        name: 'Holiday Charity Concert',
        date: new Date(2024, 11, 18),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Holiday concert with performances by the school choir!',
        ticketCost: 20,
        eventOrganizers: 'LHS Music Department',
        specialNotes: 'Donations for charity are accepted.',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['4A14', '4A15', '4A16', '4A17', '4A18', '4A19', '4A20', '4A21'],
    },
    {
        id: 'e6',
        name: 'Craft Fair 2024',
        date: new Date(2024, 10, 2),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Arts',
        location: 'Main Gymnasium',
        description:
            'Local artisan craft fair for the people interested in arts!',
        ticketCost: 10,
        eventOrganizers: 'Art Club',
        specialNotes: 'Open to the public',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1A14', '1A21', '1A22', '1A23', '1A24', '1A25', '3B13', '3B14'],
    },
    {
        id: 'e7',
        name: 'Parent-Teacher Night Conference',
        date: new Date(2024, 10, 4),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description: 'Official Meet and Greet for parents and teachers!',
        ticketCost: 0,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: '',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['4A14', '4A15', '4A16', '4A17', '4A18', '4A19', '4A20', '4A21'],
    },
    {
        id: 'e8',
        name: 'Annual Science Fair',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T17:30:00'),
        type: 'Academic',
        location: 'Cafeteria',
        description:
            'Science Fair: Showcase your awesome science projects for our students!',
        ticketCost: 5,
        eventOrganizers: 'Science Club',
        specialNotes:
            'People who do not pay the ticket fee are restricted to certain parts of the exhibit.',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['2C15', '2C16', '2C17', '3E22', '3E23', '4F10', '4F11'],
    },
    {
        id: 'e9',
        name: 'Movie Night: Screening of "Back into the Future"',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T15:00:00'),
        endTime: new Date('1970-01-01T18:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description:
            'Indoor screening of the "Back into the Future!", a revolutionary movie that will change your life for the better!',
        ticketCost: 5,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: 'Blankets and chairs will NOT be provided!',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1B10', '1B11', '1B12', '2D20', '2D21', '3G05', '3G06'],
    },
    {
        id: 'e10',
        name: 'Halloween Costume Contest',
        date: new Date(2024, 9, 31),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description:
            'Annual Halloween costume contest with prizes for the best costumes!',
        ticketCost: 5,
        eventOrganizers: 'Student Council',
        socialMedia: 'Instagram, Facebook',
        takenSeats: ['1H01', '1H02', '2A15', '2A16', '3C08', '4E30'],
    },
    {
        id: 'e11',
        name: 'Chess Club Tournament',
        date: new Date(2025, 1, 6),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Inter-school chess tournament with competitors from various schools.',
        ticketCost: 0,
        eventOrganizers: 'Chess Club',
        socialMedia: 'Instagram',
        takenSeats: ['1D10', '1D11', '2F20', '3B25', '4H15', '4H16'],
    },
    {
        id: 'e12',
        name: 'Winter Band Performance',
        date: new Date(2024, 11, 1),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T20:30:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Annual winter concert by the school band.',
        ticketCost: 15,
        eventOrganizers: 'Music Club',
        specialNotes:
            'Some parts of the seats will not be available for the time being (may change)',
        socialMedia: 'Facebook, Twitter',
        takenSeats: [],
    },
    {
        id: 'e13',
        name: 'Varsity Soccer Practice',
        date: new Date(2025, 0, 11),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T18:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description: 'Practice session for the varsity soccer team.',
        ticketCost: 0,
        eventOrganizers: 'Athletics Department',
        specialNotes:
            'People who sign up for this event will only be able to watch the kids practice.',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e14',
        name: 'Basketball Finals',
        date: new Date(2024, 11, 20),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Sports',
        location: 'Main Gymnasium',
        description: 'Championship game for varsity basketball.',
        ticketCost: 12,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e15',
        name: 'Regional Wrestling Meet',
        date: new Date(2025, 0, 20),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Regional wrestling tournament with multiple schools competing.',
        ticketCost: 10,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e16',
        name: 'Regional Wrestling Meet',
        date: new Date(2025, 1, 22),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Regional wrestling tournament with multiple schools competing.',
        ticketCost: 10,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e17',
        name: 'Spring Soccer Tournament',
        date: new Date(2025, 2, 10),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T17:00:00'),
        type: 'Sports',
        location: 'Main Field',
        description: 'Annual spring soccer tournament featuring local teams.',
        ticketCost: 15,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Instagram',
        takenSeats: [],
    },
    {
        id: 'e18',
        name: 'Science Fair',
        date: new Date(2025, 2, 18),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Education',
        location: 'Auditorium',
        description: 'Showcase of innovative student science projects.',
        ticketCost: 0,
        eventOrganizers: 'Science Club',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e19',
        name: 'Spring Musical: The Sound of Music',
        date: new Date(2025, 3, 7),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T21:30:00'),
        type: 'Theater',
        location: 'Performing Arts Center',
        description: 'School-wide production of "The Sound of Music."',
        ticketCost: 12,
        eventOrganizers: 'Drama Club',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e20',
        name: 'Charity 5K Run',
        date: new Date(2025, 3, 20),
        startTime: new Date('1970-01-01T07:00:00'),
        endTime: new Date('1970-01-01T11:00:00'),
        type: 'Sports',
        location: 'City Park',
        description: 'Annual 5K run to raise funds for local charities.',
        ticketCost: 20,
        eventOrganizers: 'Community Outreach',
        socialMedia: 'Instagram',
        takenSeats: [],
    },
    {
        id: 'e21',
        name: 'Spring Art Exhibition',
        date: new Date(2025, 4, 8),
        startTime: new Date('1970-01-01T11:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Art',
        location: 'Art Gallery',
        description: 'A showcase of student and local artist works.',
        ticketCost: 5,
        eventOrganizers: 'Art Department',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e22',
        name: 'Career Fair',
        date: new Date(2025, 4, 25),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Education',
        location: 'Gymnasium',
        description:
            'Meet potential employers and explore career opportunities.',
        ticketCost: 0,
        eventOrganizers: 'Career Services',
        socialMedia: 'LinkedIn',
        takenSeats: [],
    },
    {
        id: 'e23',
        name: "Valentine's Day Dance",
        date: new Date(2025, 1, 14),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T23:00:00'),
        type: 'Social',
        location: 'School Gym',
        description: 'A romantic evening filled with music, dancing, and fun!',
        ticketCost: 10,
        eventOrganizers: 'Student Council',
        socialMedia: 'Instagram',
        takenSeats: [],
    },
    {
        id: 'e24',
        name: 'Black History Month Panel',
        date: new Date(2025, 1, 21),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T20:00:00'),
        type: 'Education',
        location: 'Library',
        description:
            'A discussion featuring guest speakers and historical insights.',
        ticketCost: 0,
        eventOrganizers: 'Diversity Club',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e25',
        name: 'Regional Debate Competition',
        date: new Date(2025, 2, 5),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Education',
        location: 'Lecture Hall',
        description: 'Top schools compete in a high-stakes debate tournament.',
        ticketCost: 0,
        eventOrganizers: 'Debate Team',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e26',
        name: 'Spring Break Beach Cleanup',
        date: new Date(2025, 2, 28),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T12:00:00'),
        type: 'Community Service',
        location: 'Local Beach',
        description: 'Join us in keeping our beaches clean and beautiful!',
        ticketCost: 0,
        eventOrganizers: 'Environmental Club',
        socialMedia: 'Instagram',
        takenSeats: [],
    },
    {
        id: 'e27',
        name: "St. Patrick's Day Festival",
        date: new Date(2025, 2, 17),
        startTime: new Date('1970-01-01T12:00:00'),
        endTime: new Date('1970-01-01T20:00:00'),
        type: 'Festival',
        location: 'Town Square',
        description: 'Live music, food, and fun to celebrate Irish heritage!',
        ticketCost: 5,
        eventOrganizers: 'Cultural Committee',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e28',
        name: 'Tech Innovation Expo',
        date: new Date(2025, 3, 15),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Technology',
        location: 'Convention Center',
        description: 'A showcase of the latest tech projects and startups.',
        ticketCost: 8,
        eventOrganizers: 'Tech Club',
        socialMedia: 'LinkedIn',
        takenSeats: [],
    },
    {
        id: 'e29',
        name: 'Poetry Slam Night',
        date: new Date(2025, 3, 22),
        startTime: new Date('1970-01-01T18:30:00'),
        endTime: new Date('1970-01-01T21:00:00'),
        type: 'Arts',
        location: 'Café Lounge',
        description: 'An evening of powerful spoken word performances.',
        ticketCost: 5,
        eventOrganizers: 'Literature Club',
        socialMedia: 'Twitter',
        takenSeats: [],
    },
    {
        id: 'e30',
        name: 'Earth Day Tree Planting',
        date: new Date(2025, 3, 22),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T13:00:00'),
        type: 'Community Service',
        location: 'City Park',
        description: 'Help plant trees to celebrate Earth Day!',
        ticketCost: 0,
        eventOrganizers: 'Environmental Club',
        socialMedia: 'Instagram',
        takenSeats: [],
    },
    {
        id: 'e31',
        name: "April Fool's Comedy Night",
        date: new Date(2025, 3, 1),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T21:30:00'),
        type: 'Entertainment',
        location: 'Auditorium',
        description: 'A hilarious night of stand-up and improv comedy acts.',
        ticketCost: 7,
        eventOrganizers: 'Drama Club',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e32',
        name: 'Spring Farmers Market',
        date: new Date(2025, 3, 29),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Market',
        location: 'Community Center',
        description:
            'Shop fresh produce and handmade goods from local vendors.',
        ticketCost: 0,
        eventOrganizers: 'Local Business Association',
        socialMedia: 'Instagram',
        takenSeats: ['1A05', '1B15', '2C25', '3D10', '4E20', '4F30'],
    },
];
