export const BREAKS = [
    {
        startDate: new Date(2024, 7, 1),
        endDate: new Date(2024, 7, 1),
        name: 'First Day Of School',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 8, 2),
        endDate: new Date(2024, 8, 2),
        name: 'Labor Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 22),
        endDate: new Date(2024, 8, 28),
        name: 'Fall Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 9, 21),
        endDate: new Date(2024, 9, 21),
        name: 'Professional Dev. (Student Holiday)',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 10, 5),
        endDate: new Date(2024, 10, 5),
        name: 'Election Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2024, 8, 25),
        endDate: new Date(2024, 8, 26),
        name: 'Hurricane Helene Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 9, 8),
        endDate: new Date(2024, 9, 10),
        name: 'Hurricane Milton Warning',
        type: 'Disaster',
    },
    {
        startDate: new Date(2024, 10, 24),
        endDate: new Date(2024, 10, 30),
        name: 'Thanksgiving Break',
        type: 'Break',
    },
    {
        startDate: new Date(2024, 11, 21),
        endDate: new Date(2025, 0, 5),
        name: 'Winter Break',
        type: 'Break',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 0, 20),
        endDate: new Date(2025, 0, 20),
        name: 'Martin Luther King Jr. Day',
        type: 'Holiday',
    },
    {
        startDate: new Date(2025, 2, 30),
        endDate: new Date(2025, 3, 6),
        name: 'Spring Break',
        type: 'Break',
    },
    {
        startDate: new Date(2025, 1, 14),
        endDate: new Date(2025, 1, 14),
        name: 'Valentines Day',
        type: 'Holiday',
    },
];

export const AUDITORIUM_SEATS_PER_ROW = 8;
export const AUDITORIUM_SEATS_PER_ROW_SIDE = 4;
export const AUDITORIUM_ROWS = 10;

export const CONVENIENCE_FEE = 2;
export const SEATS_PER_ROW = 20;
export const SEATS_PER_ROW_SIDE = 10;
export const MAX_TICKETS_PER_PURCHASE = 6;
export const ROWS = 8;
export const EVENT_DATA = [
    {
        id: 'e1',
        name: 'Homecoming Football Game',
        date: new Date(2024, 11, 16),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description:
            'Annual homecoming game between Lambert High School and South Forsyth High School',
        ticketCost: 20,
        eventOrganizers: 'LHS Athletics Department',
        specialNotes: 'Parking Lot A and B, masks encouraged',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1A23', '1A24', '1A25', '3B13', '3B14'],
    },
    {
        id: 'e2',
        name: 'Winter Dance',
        date: new Date(2024, 11, 10),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description: 'Semi-formal dance for students, with live DJ',
        ticketCost: 35,
        eventOrganizers: 'LHS Student Council',
        specialNotes: 'Formal attire required, no re-entry policy',
        socialMedia: 'Instagram, Snapchat',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e3',
        name: 'School Play: "Romeo & Juliet"',
        date: new Date(2024, 10, 15),
        startTime: new Date('1970-01-01T14:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Theater',
        location: 'Auditorium',
        description:
            "Drama club production of Shakespeare's classic, Romeo and Juliet.",
        ticketCost: 15,
        eventOrganizers: 'State Drama Council',
        specialNotes: 'Limited seating, early booking is advised',
        socialMedia: 'Facebook, Instagram',
        takenSeats: [
            '1A14',
            '1A21',
            '1A22',
            '1A23',
            '1A24',
            '1A25',
            '3B13',
            '3B14',
        ],
    },
    {
        id: 'e4',
        name: 'Annual Science Fair',
        date: new Date(2025, 0, 24),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Science fair featuring projects from students in grades K-12',
        ticketCost: 0, // free
        eventOrganizers: 'Science Club',
        specialNotes:
            'Parking in Lot A only! Drivers who park in Lot B will automatically be escorted out.',
        socialMedia: 'Facebook, Twitter',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e5',
        name: 'Holiday Charity Concert',
        date: new Date(2024, 11, 18),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:00:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Holiday concert with performances by the school choir!',
        ticketCost: 20,
        eventOrganizers: 'LHS Music Department',
        specialNotes: 'Donations for charity are accepted.',
        socialMedia: 'Facebook, Twitter',
        takenSeats: [
            '4A14',
            '4A15',
            '4A16',
            '4A17',
            '4A18',
            '4A19',
            '4A20',
            '4A21',
        ],
    },
    {
        id: 'e6',
        name: 'Craft Fair 2024',
        date: new Date(2024, 10, 2),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Arts',
        location: 'Main Gymnasium',
        description:
            'Local artisan craft fair for the people interested in arts!',
        ticketCost: 10,
        eventOrganizers: 'Art Club',
        specialNotes: 'Open to the public',
        socialMedia: 'Facebook, Twitter',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e7',
        name: 'Parent-Teacher Night Conference',
        date: new Date(2024, 10, 4),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description: 'Official Meet and Greet for parents and teachers!',
        ticketCost: 0,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: '',
        socialMedia: 'Facebook, Twitter',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e8',
        name: 'Annual Science Fair',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T17:30:00'),
        type: 'Academic',
        location: 'Cafeteria',
        description:
            'Science Fair: Showcase your awesome science projects for our students!',
        ticketCost: 5,
        eventOrganizers: 'Science Club',
        specialNotes:
            'People who do not pay the ticket fee are restricted to certain parts of the exhibit.',
        socialMedia: 'Facebook, Twitter',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e9',
        name: 'Movie Night: Screening of "Back into the Future"',
        date: new Date(2024, 10, 7),
        startTime: new Date('1970-01-01T15:00:00'),
        endTime: new Date('1970-01-01T18:30:00'),
        type: 'Social',
        location: 'Auditorium',
        description:
            'Indoor screening of the "Back into the Future!", a revolutionary movie that will change your life for the better!',
        ticketCost: 5,
        eventOrganizers: 'LHS Counseling Team',
        specialNotes: 'Blankets and chairs will NOT be provided!',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1B10', '1B11', '1B12', '2D20', '2D21', '3G05', '3G06'],
    },
    {
        id: 'e10',
        name: 'Halloween Costume Contest',
        date: new Date(2024, 9, 31),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description:
            'Annual Halloween costume contest with prizes for the best costumes!',
        ticketCost: 5,
        eventOrganizers: 'Student Council',
        socialMedia: 'Instagram, Facebook',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e11',
        name: 'Chess Club Tournament',
        date: new Date(2025, 2, 16),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Academic',
        location: 'Main Gymnasium',
        description:
            'Inter-school chess tournament with competitors from various schools.',
        ticketCost: 0,
        eventOrganizers: 'Chess Club',
        socialMedia: 'Instagram',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e12',
        name: 'Winter Band Performance',
        date: new Date(2024, 11, 1),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T20:30:00'),
        type: 'Music',
        location: 'Auditorium',
        description: 'Annual winter concert by the school band.',
        ticketCost: 15,
        eventOrganizers: 'Music Club',
        specialNotes:
            'Some parts of the seats will not be available for the time being (may change)',
        socialMedia: 'Facebook, Twitter',
        takenSeats: ['1A1', '1A2', '1A3', '1C3', '1C4', '1C5', '2A10', '3B8'],
    },
    {
        id: 'e13',
        name: 'Varsity Soccer Practice',
        date: new Date(2025, 0, 11),
        startTime: new Date('1970-01-01T16:00:00'),
        endTime: new Date('1970-01-01T18:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description: 'Practice session for the varsity soccer team.',
        ticketCost: 0,
        eventOrganizers: 'Athletics Department',
        specialNotes:
            'People who sign up for this event will only be able to watch the kids practice.',
        socialMedia: 'Twitter',
        takenSeats: [
            '1A1',
            '1A2',
            '1A3',
            '1A4',
            '1A5',
            '1A6',
            '1A7',
            '1A8',
            '1A9',
            '1A10',
            '1A11',
            '1A12',
            '1A13',
            '1A14',
            '1A15',
            '1A16',
            '1A17',
            '1A18',
            '1A19',
            '1A20',
        ],
    },
    {
        id: 'e14',
        name: 'Basketball Finals',
        date: new Date(2024, 11, 20),
        startTime: new Date('1970-01-01T17:00:00'),
        endTime: new Date('1970-01-01T19:30:00'),
        type: 'Sports',
        location: 'Main Gymnasium',
        description: 'Championship game for varsity basketball.',
        ticketCost: 12,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Twitter',
        takenSeats: ['4B23', '3A12'],
    },
    {
        id: 'e15',
        name: 'Regional Wrestling Meet',
        date: new Date(2025, 0, 20),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Sports',
        location: 'Main Gymnasium',
        description:
            'Regional wrestling tournament with multiple schools competing.',
        ticketCost: 10,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Facebook',
        takenSeats: [],
    },
    {
        id: 'e16',
        name: 'Regional Wrestling Meet',
        date: new Date(2025, 2, 22),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Sports',
        location: 'Main Gymnasium',
        description:
            'Regional wrestling tournament with multiple schools competing.',
        ticketCost: 10,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Facebook',
        takenSeats: ['1A5', '1B7', '2C12', '3D15', '4E8', '4F19'],
    },
    {
        id: 'e17',
        name: 'Spring Soccer Tournament',
        date: new Date(2025, 2, 14),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T17:00:00'),
        type: 'Sports',
        location: 'Main Field',
        description: 'Annual spring soccer tournament featuring local teams.',
        ticketCost: 15,
        eventOrganizers: 'Athletics Department',
        socialMedia: 'Instagram',
        takenSeats: ['1C3', '1C4', '1C5', '2A10', '3B8', '4H15', '4H16'],
    },
    {
        id: 'e18',
        name: 'Science Fair',
        date: new Date(2025, 2, 18),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Education',
        location: 'Auditorium',
        description: 'Showcase of innovative student science projects.',
        ticketCost: 0,
        eventOrganizers: 'Science Club',
        socialMedia: 'Twitter',
        takenSeats: [ '2D3', '2D4' ],
    },
    {
        id: 'e19',
        name: 'Spring Musical: The Sound of Music',
        date: new Date(2025, 3, 7),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T21:30:00'),
        type: 'Theater',
        location: 'Auditorium',
        description: 'School-wide production of "The Sound of Music."',
        ticketCost: 12,
        eventOrganizers: 'Drama Club',
        socialMedia: 'Facebook',
        takenSeats: ['1H1', '1H2', '2A15', '3B8', '4C12', '4D5'],
    },
    {
        id: 'e20',
        name: 'Charity 5K Run',
        date: new Date(2025, 3, 20),
        startTime: new Date('1970-01-01T07:00:00'),
        endTime: new Date('1970-01-01T11:00:00'),
        type: 'Sports',
        location: 'Stadium',
        description: 'Annual 5K run to raise funds for local charities.',
        ticketCost: 20,
        eventOrganizers: 'Community Outreach',
        socialMedia: 'Instagram',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e21',
        name: 'Spring Art Exhibition',
        date: new Date(2025, 4, 8),
        startTime: new Date('1970-01-01T11:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Art',
        location: 'Main Gymnasium',
        description: 'A showcase of student and local artist works.',
        ticketCost: 5,
        eventOrganizers: 'Art Department',
        socialMedia: 'Twitter',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e22',
        name: 'Career Fair',
        date: new Date(2025, 4, 25),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T15:00:00'),
        type: 'Education',
        location: 'Main Gymnasium',
        description:
            'Meet potential employers and explore career opportunities.',
        ticketCost: 0,
        eventOrganizers: 'Career Services',
        socialMedia: 'LinkedIn',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e24',
        name: 'Prom Night',
        date: new Date(2025, 3, 18),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T23:00:00'),
        type: 'Social',
        location: 'Main Gymnasium',
        description: 'A romantic evening filled with music, dancing, and fun!',
        ticketCost: 30,
        eventOrganizers: 'Student Council',
        socialMedia: 'Instagram',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e25',
        name: 'Black History Month Panel',
        date: new Date(2025, 1, 21),
        startTime: new Date('1970-01-01T18:00:00'),
        endTime: new Date('1970-01-01T20:00:00'),
        type: 'Education',
        location: 'Library',
        description:
            'A discussion featuring guest speakers and historical insights.',
        ticketCost: 0,
        eventOrganizers: 'Diversity Club',
        socialMedia: 'Facebook',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e26',
        name: 'Regional Debate Competition',
        date: new Date(2025, 2, 20),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Education',
        location: 'Main Gymnasium',
        description: 'Top schools compete in a high-stakes debate tournament.',
        ticketCost: 0,
        eventOrganizers: 'Debate Team',
        socialMedia: 'Twitter',
        takenSeats: ['1F8', '2G12', '3H5', '3A10', '4B15', '4C8'],
    },

    {
        id: 'e27',
        name: "St. Patrick's Day Festival",
        date: new Date(2025, 2, 17),
        startTime: new Date('1970-01-01T12:00:00'),
        endTime: new Date('1970-01-01T20:00:00'),
        type: 'Festival',
        location: 'Main Gymnasium',
        description: 'Live music, food, and fun to celebrate Irish heritage!',
        ticketCost: 5,
        eventOrganizers: 'Cultural Committee',
        socialMedia: 'Facebook',
        takenSeats: ['1H5', '2A10', '3B15', '3C8', '4D12', '4E5'],
    },
    {
        id: 'e28',
        name: 'Tech Innovation Expo',
        date: new Date(2025, 3, 15),
        startTime: new Date('1970-01-01T10:00:00'),
        endTime: new Date('1970-01-01T16:00:00'),
        type: 'Technology',
        location: 'Main Gymnasium',
        description: 'A showcase of the latest tech projects and startups.',
        ticketCost: 8,
        eventOrganizers: 'Tech Club',
        socialMedia: 'LinkedIn',
        takenSeats: ['1A8', '2B12', '3C5', '3D10', '4E15', '4F8'],
    },
    {
        id: 'e29',
        name: 'Poetry Slam Night',
        date: new Date(2025, 3, 22),
        startTime: new Date('1970-01-01T18:30:00'),
        endTime: new Date('1970-01-01T21:00:00'),
        type: 'Arts',
        location: 'Main Gymnasium',
        description: 'An evening of powerful spoken word performances.',
        ticketCost: 5,
        eventOrganizers: 'Literature Club',
        socialMedia: 'Twitter',
        takenSeats: ['1B12', '2C5', '3D8', '3E12', '4F5', '4G10'],
    },
    {
        id: 'e30',
        name: 'Earth Day Tree Planting',
        date: new Date(2025, 3, 22),
        startTime: new Date('1970-01-01T09:00:00'),
        endTime: new Date('1970-01-01T13:00:00'),
        type: 'Community Service',
        location: 'Main Field',
        description: 'Help plant trees to celebrate Earth Day!',
        ticketCost: 0,
        eventOrganizers: 'Environmental Club',
        socialMedia: 'Instagram',
        noSeats: true,
        takenSeats: [],
    },
    {
        id: 'e31',
        name: "April Fool's Comedy Night",
        date: new Date(2025, 3, 1),
        startTime: new Date('1970-01-01T19:00:00'),
        endTime: new Date('1970-01-01T21:30:00'),
        type: 'Entertainment',
        location: 'Auditorium',
        description: 'A hilarious night of stand-up and improv comedy acts.',
        ticketCost: 7,
        eventOrganizers: 'Drama Club',
        socialMedia: 'Facebook',
        takenSeats: ['1D8', '2E12', '3F5', '3G10', '4H15', '4A8'],
    },
    {
        id: 'e32',
        name: 'Spring Farmers Market',
        date: new Date(2025, 3, 29),
        startTime: new Date('1970-01-01T08:00:00'),
        endTime: new Date('1970-01-01T14:00:00'),
        type: 'Market',
        location: 'Main Gymnasium',
        description:
            'Shop fresh produce and handmade goods from local vendors.',
        ticketCost: 0,
        eventOrganizers: 'Local Business Association',
        socialMedia: 'Instagram',
        noSeats: true,
        takenSeats: [],
    },
];
